// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261001131345_InitialCreateDatabase")]
    partial class InitialCreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Snack, bánh quy, kẹo dẻo"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước giải khát & Trà",
                            Description = "Nước ngọt, nước khoáng, trà"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa & Sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, phô mai"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì gói & Thực phẩm ăn liền",
                            Description = "Mì ăn liền, phở khô, cháo gói"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị & Dầu ăn",
                            Description = "Nước mắm, hạt nêm, dầu thực vật"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Rau củ & Trái cây",
                            Description = "Rau xanh, trái cây, nông sản tươi"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Thịt & Hải sản",
                            Description = "Thịt heo, gà, cá, tôm"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Đồ hộp & Đóng gói",
                            Description = "Đồ hộp, thực phẩm lưu trữ"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Q.1, TP.HCM",
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Q.7, TP.HCM",
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Q.3, TP.HCM",
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 10
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Q.5, TP.HCM",
                            CustomerName = "Phạm Thị D",
                            MembershipRank = "Kim cương",
                            PhoneNumber = "0909988776",
                            RewardPoints = 320
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Q.10, TP.HCM",
                            CustomerName = "Hoàng Văn E",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0912345678",
                            RewardPoints = 80
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "Q.12, TP.HCM",
                            CustomerName = "Nguyễn Thị F",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0977665544",
                            RewardPoints = 210
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "Q.4, TP.HCM",
                            CustomerName = "Đỗ Văn G",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0966554433",
                            RewardPoints = 25
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "Q.2, TP.HCM",
                            CustomerName = "Mai Thị H",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0932456789",
                            RewardPoints = 70
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "Q.8, TP.HCM",
                            CustomerName = "Vũ Văn K",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0922334455",
                            RewardPoints = 140
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "Q.11, TP.HCM",
                            CustomerName = "Lý Thị M",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0944556677",
                            RewardPoints = 60
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "893500123001",
                            CategoryId = 1,
                            Price = 18000m,
                            ProductName = "Oishi Snack Seaweed",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "893500123002",
                            CategoryId = 1,
                            Price = 22000m,
                            ProductName = "Bánh quy bơ sữa",
                            StockQuantity = 85
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "893500123003",
                            CategoryId = 1,
                            Price = 15000m,
                            ProductName = "Kẹo mềm dâu tây",
                            StockQuantity = 140
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "893500123004",
                            CategoryId = 2,
                            Price = 12000m,
                            ProductName = "Coca Cola 330ml",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "893500123005",
                            CategoryId = 2,
                            Price = 7000m,
                            ProductName = "Nước suối Lavie 500ml",
                            StockQuantity = 250
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "893500123006",
                            CategoryId = 2,
                            Price = 16000m,
                            ProductName = "Trà xanh không độ",
                            StockQuantity = 110
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "893500123007",
                            CategoryId = 3,
                            Price = 23000m,
                            ProductName = "Sữa tươi Vinamilk",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "893500123008",
                            CategoryId = 3,
                            Price = 18000m,
                            ProductName = "Sữa chua ăn hương dâu",
                            StockQuantity = 130
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "893500123009",
                            CategoryId = 3,
                            Price = 52000m,
                            ProductName = "Phô mai mozzarella",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "893500123010",
                            CategoryId = 4,
                            Price = 9000m,
                            ProductName = "Mì Gấu Đỏ 65g",
                            StockQuantity = 180
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "893500123011",
                            CategoryId = 4,
                            Price = 14000m,
                            ProductName = "Phở khô bò hầm",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "893500123012",
                            CategoryId = 4,
                            Price = 11000m,
                            ProductName = "Cháo gói thịt nấm",
                            StockQuantity = 160
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "893500123013",
                            CategoryId = 5,
                            Price = 30000m,
                            ProductName = "Nước mắm Nam Ngư",
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "893500123014",
                            CategoryId = 5,
                            Price = 12000m,
                            ProductName = "Muối hạt tiêu",
                            StockQuantity = 95
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "893500123015",
                            CategoryId = 5,
                            Price = 36000m,
                            ProductName = "Dầu ăn Neptune 1L",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 16,
                            Barcode = "893500123016",
                            CategoryId = 6,
                            Price = 15000m,
                            ProductName = "Rau cải xanh",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 17,
                            Barcode = "893500123017",
                            CategoryId = 6,
                            Price = 45000m,
                            ProductName = "Táo Mỹ",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 18,
                            Barcode = "893500123018",
                            CategoryId = 6,
                            Price = 28000m,
                            ProductName = "Cam sành",
                            StockQuantity = 110
                        },
                        new
                        {
                            ProductId = 19,
                            Barcode = "893500123019",
                            CategoryId = 7,
                            Price = 92000m,
                            ProductName = "Thịt heo ba rọi",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 20,
                            Barcode = "893500123020",
                            CategoryId = 7,
                            Price = 99000m,
                            ProductName = "Cá basa tươi",
                            StockQuantity = 36
                        },
                        new
                        {
                            ProductId = 21,
                            Barcode = "893500123021",
                            CategoryId = 7,
                            Price = 180000m,
                            ProductName = "Tôm sú thẻ",
                            StockQuantity = 28
                        },
                        new
                        {
                            ProductId = 22,
                            Barcode = "893500123022",
                            CategoryId = 8,
                            Price = 17000m,
                            ProductName = "Đậu đóng hộp",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 23,
                            Barcode = "893500123023",
                            CategoryId = 8,
                            Price = 21000m,
                            ProductName = "Nước sốt cà chua",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 24,
                            Barcode = "893500123024",
                            CategoryId = 8,
                            Price = 24000m,
                            ProductName = "Đồ hộp ngũ cốc",
                            StockQuantity = 60
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
